version: "3.9"

services:

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        ports:
            - 5173:5173
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ../frontend/:/app:delegated
            - /app/node_modules

    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "5000:5000"
        environment:
            MONGO_URI: 'mongodb://localhost:27017/User-Behavior-Driven-Interface'
            DATABASE_NAME: 'User-Behavior-Driven-Interface'
            PORT: 5000
            FLASK_DEBUG: 1
            HOST: 'mongodb'
        depends_on:
            - mongo-db
        volumes:
            - '../backend/:/app/'

    mongo-db:
        image: mongo:latest
        hostname: mongo
        ports:
            - "27018:27017"
        container_name: mongo-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo-data:/data/db
    
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo-db:27017/

volumes:
  mongo-data:
    driver: local
