TEST_TRANSFER_TITLE = "cyclicPaymentName"
TEST_BANK_ACCOUNT_NUMBER = "00000000000000000000000000"
TEST_RECIPIENT_ACCOUNT_NUMBER = "11111111111111111111111111"
TEST_AMOUNT = "5"
TEST_LOAN_AMOUNT = 2000
TEST_LOAN_AMOUNT_TOO_LOW = 999
TEST_LOAN_AMOUNT_TOO_BIG = 100001
TEST_MIN_LOAN_AMOUNT = 1000
TEST_MAX_LOAN_AMOUNT = 100000
TEST_LOAN_AMOUNT_NOT_THOUSANDS = 4004

DEFAULT_TRANSFER_LOAN = {
    'transferTitle': TEST_TRANSFER_TITLE,
    'amount': TEST_LOAN_AMOUNT,
}

DEFAULT_TRANSFER_LOAN_TOO_LOW = {
    'transferTitle': TEST_TRANSFER_TITLE,
    'amount': TEST_LOAN_AMOUNT_TOO_LOW,
}

DEFAULT_TRANSFER_LOAN_TOO_BIG = {
    'transferTitle': TEST_TRANSFER_TITLE,
    'amount': TEST_LOAN_AMOUNT_TOO_BIG,
}

DEFAULT_TRANSFER_LOAN_NOT_THOUSANDS = {
    'transferTitle': TEST_TRANSFER_TITLE,
    'amount': TEST_LOAN_AMOUNT_NOT_THOUSANDS,
}

DEFAULT_TRANSFER = {
    'recipientAccountNumber': TEST_RECIPIENT_ACCOUNT_NUMBER,
    'transferTitle': TEST_TRANSFER_TITLE,
    'amount': TEST_AMOUNT,
}

INVALID_TRANSFER = {
    'recipientAccountNumber': TEST_RECIPIENT_ACCOUNT_NUMBER,
    'amount': TEST_AMOUNT,
}

TEST_YEAR = 2024
TEST_YEAR_INVALID = "2024"
